#!/usr/bin/env python
# coding: utf-8

# New Currency Prices
# 
# Hi there, we need to add British Pound and Japanese Yen pricing to our 'Item_Info' sheet in the Maven data Excel workbook.
# 
# I've included the code to read in the excel workbook below.
# 

# In[52]:


import openpyxl as excel_library
workbook = excel_library.load_workbook(filename=r"Python Foundations and Data Analysis\Python+Course+Assignments\Python Course Assignments\Section12_excel\maven_ski_shop_data.xlsx")
workbook.sheetnames
item_info = workbook['Item_Info']


# Currency Converter
# 
# Since we're going to be doing this a few times (and hopefully more in the future), let's create a currency_converter function to take a price, and an exchange rate, returning a converted price rounded to two decimal places.

# In[53]:


def currency_converter(price , rate ):
    conversion = price * rate
    rounding_conversion = round(conversion , 2)
    return rounding_conversion


# Convert to Euro
# 
# Now that you know how to do an the pounds do the Euro
# Conversion Rate 1 Euro = 1.08 Dollars 

# In[54]:


euro_exchange_rate = 0.92

for index , cell_value in enumerate( item_info['C'] , start= 1 ):
    if index == 1:
        item_info[f'I{index}'] = "Euro Exchange 2023"
    else:
        item_info[f'I{index}'] = currency_converter( cell_value.value , euro_exchange_rate )


# In[55]:


for values in item_info['I']:
    print(values.value)


# British Pound Column
# 
# Now that we have a currency converter, create a column with British Pound prices, in the column to the right of the Euro prices.
# 
# Don't forget to add a column title - 'GBP Price' Should Work!

# In[56]:


pound_exchange_rate = 0.76

for index , cell_conversion in enumerate(item_info['C'] , start = 1 ):
    if index == 1: 
        item_info[f'G{index}'] = "GBP Price"
    else:
        item_info[f'G{index}'] = currency_converter(float(cell_conversion.value) , pound_exchange_rate)
         


# Japanese Yen Column
# Next, create a Japanese Yen Column with the same method we did for British Pounds.
# 
# Call this column 'JPY Price'

# In[57]:


yen_exchange_rate = 123

for index , cell_value in enumerate(item_info['C'] , start = 1):
    if index == 1:
        item_info[f"H{index}"] = "JPY Price"
    else:
        item_info[f"H{index}"] = currency_converter(cell_value.value ,  yen_exchange_rate)


# In[58]:


workbook.save(r"Escritorio\test_file_2.xlsx")


# In[ ]:




